# Generated by Django 3.1.3 on 2020-11-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
